#ifndef PIN_DEFINITIONS_H
#define PIN_DEFINITIONS_H

#define LED1 PD0
#define LED2 PC0
#define LED3 PD1

#define PORT_LED1 PORTD
#define PORT_LED2 PORTC
#define PORT_LED3 PORTD

#define POT PD6 //ADC3
#define PORT_POT PORTD

#define BUTTON1 0 //PCINT23
#define BUTTON2 1 //PCINT0
#define BUTTON3 2 //PCINT1

/* FLAG DEFINITIONS */
#define UPDATE_DISPLAY 0

#endif
